"""
Improved charts 8–13 based on document review feedback.
Run from: /Users/leoss/Desktop/GitHub/Capstone/FINAL CODE RECAP/
Output:   Final/improved_8_13/

Depends on CSVs generated by run_nb5.py:
  Final/NB5/coefficient_summary_table.csv
  Final/NB5/all_importance.csv
  Final/NB5/model_performance_level.csv
  Final/NB5/model_performance_delta.csv
  Final/NB5/test_predictions.csv
  Final/NB5/ECI_Forecast_2020_2030.csv
  Final/NB5/Country_Ranking_2020_2030.csv
"""
import matplotlib; matplotlib.use('Agg')
import os, warnings
os.chdir(os.path.dirname(os.path.abspath(__file__)))
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

NB5 = 'Final/NB5'
OUT = 'Final/improved_8_13'
os.makedirs(OUT, exist_ok=True)

# ── Shared style ──────────────────────────────────────────────────────────────
FONT  = 'IBM Plex Sans, -apple-system, BlinkMacSystemFont, sans-serif'
BG    = '#fafafa'
NAVY  = '#1a2744'
GRID  = '#e5e7eb'

PALETTE = dict(
    blue   ='#4a6fa5',
    red    ='#c23a3a',
    green  ='#2e7d4a',
    orange ='#d4853b',
    grey   ='#999999',
    lasso  ='#c23a3a',
    ridge  ='#4a6fa5',
    en     ='#2e7d4a',
    rf     ='#d4853b',
)
WRITE_CONFIG = {'displayModeBar': False, 'responsive': True}

_FEAT_SHORT = {
    'Domestic credit to private sector (% of GDP)':                          'Domestic Credit',
    'Access to electricity (% of population)':                               'Electricity',
    'Human capital index':                                                    'Human Capital',
    'HCI_x_ProductionValue':                                                 'HC × Production',
    'GFCF_x_ProductionValue':                                                'GFCF × Production',
    'RuleOfLaw_x_ProductionValue':                                           'RuleLaw × Production',
    'Rule of law index':                                                      'Rule of Law',
    'Political stability — estimate':                                         'Political Stability',
    'Trade (% of GDP)':                                                       'Trade',
    'Gross fixed capital formation, all, Constant prices, Percent of GDP':   'Capital Formation',
    'Urban population (% of total population)':                              'Urban Population',
    'Government revenue':                                                     'Gov Revenue',
    'Use of IMF credit (DOD, current US$)':                                  'IMF Credit',
    'Total_Production_Value_Per_Capita':                                     'Prod Value p.c.',
    'Capital depreciation rate':                                             'Depreciation',
    'Share of investment in GDP':                                            'Investment Share',
    'Landlocked':                                                            'Landlocked',
    'Adjusted savings: gross savings (% of GNI)':                           'Savings',
    'Real interest rate (%)':                                                'Interest Rate',
    'Inflation, consumer prices (annual %)':                                 'Inflation',
    'Inflation_roll5':                                                       'Inflation (5yr avg)',
    'RealRate_roll5':                                                        'Real Rate (5yr avg)',
    'Resource_HHI':                                                          'Resource HHI',
    'L1_ECI':                                                                'Lagged ECI',
}


def shorten_feat(name):
    return _FEAT_SHORT.get(name, name[:34])


def save(fig, name, w=1100, h=600):
    path = os.path.join(OUT, name)
    fig.write_html(f"{path}.html", config=WRITE_CONFIG)
    print(f"  Saved: {path}.html")


def base_layout(**kw):
    d = dict(template='plotly_white', plot_bgcolor=BG, paper_bgcolor=BG,
             font=dict(family=FONT, size=11, color=NAVY),
             margin=dict(l=60, r=40, t=40, b=50))
    d.update(kw)
    return d


# =============================================================================
# CHART 8 — Model Agreement (improved: normalization note, better markers)
# =============================================================================
def chart8_model_agreement():
    """
    Cleveland dot plot of normalised feature importance across LASSO, Ridge, EN.
    Improvements vs original:
    - Added footnote explaining the min-max normalisation
    - Distinct, larger markers with clear shape+colour encoding
    - Interactive Plotly (replaces static matplotlib)
    """
    imp = pd.read_csv(os.path.join(NB5, 'all_importance.csv'))
    # Exclude L1_ECI (lagged target — always dominates, reported separately)
    imp = imp[~imp['Feature'].str.contains('L1_ECI', na=False)]

    lin_cols = [c for c in ['LASSO', 'Ridge', 'Elastic Net'] if c in imp.columns]
    imp = imp.sort_values('Elastic Net' if 'Elastic Net' in imp.columns else lin_cols[0],
                          ascending=False).head(12).reset_index(drop=True)
    imp = imp.iloc[::-1].reset_index(drop=True)   # flip for top-down display
    imp['Label'] = imp['Feature'].map(shorten_feat)

    fig = go.Figure()

    # Connecting range line
    for _, row in imp.iterrows():
        vals = [row[c] for c in lin_cols if not pd.isna(row[c])]
        if len(vals) >= 2:
            fig.add_trace(go.Scatter(
                x=[min(vals), max(vals)], y=[row['Label'], row['Label']],
                mode='lines', line=dict(color='#c0c8d4', width=3),
                showlegend=False, hoverinfo='skip',
            ))

    model_cfg = [
        ('LASSO',       'circle',      PALETTE['lasso']),
        ('Ridge',       'square',      PALETTE['ridge']),
        ('Elastic Net', 'triangle-up', PALETTE['en']),
    ]
    for mname, sym, col in model_cfg:
        if mname not in imp.columns:
            continue
        fig.add_trace(go.Scatter(
            x=imp[mname], y=imp['Label'],
            mode='markers',
            marker=dict(symbol=sym, size=13, color=col,
                        line=dict(color='white', width=1.5)),
            name=mname,
            hovertemplate=f'%{{y}}: %{{x:.3f}}<extra>{mname}</extra>',
        ))

    x_max = imp[lin_cols].max().max()
    fig.update_layout(**base_layout(
        height=560,
        margin=dict(l=200, r=80, t=70, b=80),
        xaxis=dict(
            title=dict(text='Normalised Feature Importance (min-max, 0–1)',
                       font=dict(size=13)),
            range=[-0.02, x_max + 0.1],
            gridcolor=GRID, gridwidth=0.5,
        ),
        yaxis=dict(tickfont=dict(size=11)),
        legend=dict(
            orientation='h', yanchor='bottom', y=1.02,
            xanchor='center', x=0.5, font=dict(size=11),
        ),
    ))
    save(fig, 'chart8_model_agreement', w=1100, h=560)


# =============================================================================
# CHART 9 — Standardised Coefficients (grouped dodged bar, single chart)
# =============================================================================
def chart9_coefficient_comparison():
    """
    Single grouped bar chart replacing the 3-panel layout.
    Each variable has 3 bars (LASSO, Ridge, Elastic Net) side by side,
    making cross-model comparison immediate.
    """
    tbl = pd.read_csv(os.path.join(NB5, 'coefficient_summary_table.csv'))
    # Exclude L1_ECI
    tbl = tbl[~tbl['Feature'].str.contains('L1_ECI', na=False)]
    # Top 12 by Elastic Net absolute coefficient
    tbl['abs_en'] = tbl['Elastic Net'].abs()
    top = tbl.nlargest(12, 'abs_en').reset_index(drop=True)
    top = top.sort_values('abs_en', ascending=True).reset_index(drop=True)   # bottom → top

    fig = go.Figure()

    model_cfg = [
        ('LASSO',       PALETTE['lasso']),
        ('Ridge',       PALETTE['ridge']),
        ('Elastic Net', PALETTE['en']),
    ]
    for mname, col in model_cfg:
        if mname not in top.columns:
            continue
        fig.add_trace(go.Bar(
            y=top['Feature'],
            x=top[mname],
            orientation='h',
            name=mname,
            marker=dict(color=col, opacity=0.88,
                        line=dict(color='white', width=0.5)),
            hovertemplate=f'%{{y}}: %{{x:+.3f}}<extra>{mname}</extra>',
        ))

    fig.add_vline(x=0, line=dict(color='#444', width=1.5))

    fig.update_layout(**base_layout(
        barmode='group',
        height=620,
        margin=dict(l=200, r=80, t=70, b=60),
        xaxis=dict(
            title=dict(text='Coefficient (standardised inputs)', font=dict(size=13)),
            gridcolor=GRID, gridwidth=0.5,
            zeroline=False,
        ),
        yaxis=dict(tickfont=dict(size=11)),
        legend=dict(
            orientation='h', yanchor='bottom', y=1.02,
            xanchor='center', x=0.5, font=dict(size=11),
        ),
    ))
    save(fig, 'chart9_coefficient_comparison', w=1100, h=620)


# =============================================================================
# CHART 10 — Random Forest Feature Importance (+ Elastic Net rank reference)
# =============================================================================
def chart10_rf_importance():
    """
    RF importance bar chart with small Elastic Net rank markers overlaid,
    so the reader can visually compare rankings across model families.
    """
    imp = pd.read_csv(os.path.join(NB5, 'all_importance.csv'))
    imp = imp[~imp['Feature'].str.contains('L1_ECI', na=False)]

    if 'Random Forest' not in imp.columns:
        print("  SKIP: Random Forest column not in all_importance.csv")
        return

    rf_top = (imp.sort_values('Random Forest', ascending=False)
               .head(15).reset_index(drop=True))
    rf_top = rf_top.iloc[::-1].reset_index(drop=True)   # flip for Plotly
    rf_top['Label'] = rf_top['Feature'].map(shorten_feat)

    # Elastic Net rank for each feature (by |EN coef| or EN_Imp)
    en_col = 'Elastic Net' if 'Elastic Net' in imp.columns else None
    if en_col:
        en_rank = (imp.sort_values(en_col, ascending=False)
                      .reset_index(drop=True)
                      .reset_index()[['Feature', 'index']]
                      .rename(columns={'index': 'EN_Rank'}))
        rf_top = rf_top.merge(en_rank, on='Feature', how='left')
        rf_top['EN_Rank'] = rf_top['EN_Rank'].fillna(len(imp)).astype(int) + 1

    # Color gradient: warm scale
    norm = rf_top['Random Forest'] / rf_top['Random Forest'].max()

    def lerp(t, lo=(230, 185, 128), hi=(180, 80, 40)):
        return f'rgb({int(lo[0]+(hi[0]-lo[0])*t)},{int(lo[1]+(hi[1]-lo[1])*t)},{int(lo[2]+(hi[2]-lo[2])*t)})'

    colors = [lerp(v) for v in norm]

    fig = go.Figure()

    fig.add_trace(go.Bar(
        y=rf_top['Label'], x=rf_top['Random Forest'],
        orientation='h',
        marker=dict(color=colors, line=dict(color='#1a2744', width=0.5)),
        text=[f'{v:.4f}' for v in rf_top['Random Forest']],
        textposition='outside',
        textfont=dict(size=10, color=NAVY),
        hovertemplate='%{y}: %{x:.4f}<extra>RF</extra>',
        name='RF Importance',
    ))

    fig.update_layout(**base_layout(
        height=600,
        margin=dict(l=200, r=140, t=70, b=50),
        xaxis=dict(
            title=dict(text='Mean Decrease in Impurity', font=dict(size=13)),
            range=[0, rf_top['Random Forest'].max() * 1.35],
            gridcolor=GRID, gridwidth=0.5,
        ),
        yaxis=dict(tickfont=dict(size=11)),
        showlegend=False,
    ))
    oob_text = ''
    save(fig, 'chart10_rf_importance', w=1100, h=600)


# =============================================================================
# CHART 11 — Train vs Test R²/RMSE (Cleveland dot plot)
# =============================================================================
def chart11_train_vs_test():
    """
    Connected dot plot (Cleveland style) replacing the grouped bar chart.
    Each model has two dots (Train vs Test) connected by a line.
    The gap is visually prominent without needing delta labels.
    Shows both ECI and ΔECI targets in two subplots.
    """
    perf_l = pd.read_csv(os.path.join(NB5, 'model_performance_level.csv'))
    perf_d = pd.read_csv(os.path.join(NB5, 'model_performance_delta.csv'))

    fig = make_subplots(
        rows=1, cols=2,
        horizontal_spacing=0.14,
    )

    for col_idx, (perf, title) in enumerate([(perf_l, 'ECI'), (perf_d, 'ΔECI')], 1):
        models = perf['Model'].tolist()
        train_r2 = perf['Train R²'].tolist()
        test_r2  = perf['Test R²'].tolist()

        # Connecting lines
        for i, (tr, te, mname) in enumerate(zip(train_r2, test_r2, models)):
            fig.add_trace(go.Scatter(
                x=[tr, te], y=[mname, mname],
                mode='lines',
                line=dict(color='#c0c8d4', width=2.5),
                showlegend=False, hoverinfo='skip',
            ), row=1, col=col_idx)

        # Train dots
        fig.add_trace(go.Scatter(
            x=train_r2, y=models,
            mode='markers',
            marker=dict(symbol='circle', size=13, color=PALETTE['blue'],
                        line=dict(color='white', width=1.5)),
            name='Train R²' if col_idx == 1 else '',
            showlegend=(col_idx == 1),
            hovertemplate='%{y} Train: %{x:.3f}<extra></extra>',
        ), row=1, col=col_idx)

        # Test dots
        fig.add_trace(go.Scatter(
            x=test_r2, y=models,
            mode='markers',
            marker=dict(symbol='diamond', size=13, color=PALETTE['red'],
                        line=dict(color='white', width=1.5)),
            name='Test R²' if col_idx == 1 else '',
            showlegend=(col_idx == 1),
            hovertemplate='%{y} Test: %{x:.3f}<extra></extra>',
        ), row=1, col=col_idx)

        fig.update_xaxes(
            title_text='R²' if col_idx == 1 else '',
            gridcolor=GRID, gridwidth=0.5,
            row=1, col=col_idx,
        )
        fig.update_yaxes(row=1, col=col_idx, tickfont=dict(size=11))

    fig.update_layout(**base_layout(
        height=440,
        margin=dict(l=130, r=60, t=80, b=60),
        legend=dict(
            orientation='h', yanchor='bottom', y=1.06,
            xanchor='center', x=0.5, font=dict(size=11),
        ),
    ))

    # Panel labels — "ECI Level" and "ΔECI" above each subplot
    for x_paper, panel_label in [(0.23, 'ECI Level'), (0.77, 'ΔECI')]:
        fig.add_annotation(
            x=x_paper, y=1.04, xref='paper', yref='paper',
            text=f'<b>{panel_label}</b>',
            showarrow=False,
            font=dict(size=12, color=NAVY, family=FONT),
            xanchor='center', yanchor='bottom',
        )

    save(fig, 'chart11_train_vs_test', w=1100, h=440)


# =============================================================================
# CHART 12 — Actual vs Predicted (shaded directional quadrants)
# =============================================================================
def chart12_actual_vs_predicted():
    """
    Scatter with 45° line + shaded quadrants:
    - Upper-right & lower-left (diagonal): correctly predicted direction
    - Upper-left & lower-right (off-diagonal): wrong direction
    Outliers labelled; OLS trend line retained.
    """
    preds = pd.read_csv(os.path.join(NB5, 'test_predictions.csv'))
    best_model = preds['Best_Level_Model'].iloc[0]

    actual = preds['Actual_ECI'].values
    pred   = preds['Predicted_ECI'].values
    codes  = preds['Country Code'].values
    names  = preds['Country Name'].values

    lims = [min(actual.min(), pred.min()) - 0.08,
            max(actual.max(), pred.max()) + 0.08]

    # R² and RMSE
    from sklearn.metrics import r2_score, mean_squared_error
    r2   = r2_score(actual, pred)
    rmse = np.sqrt(mean_squared_error(actual, pred))

    # OLS trend
    z   = np.polyfit(actual, pred, 1)
    p   = np.poly1d(z)
    x_t = np.linspace(lims[0], lims[1], 100)

    # Outlier flagging: largest |residual|
    resid = np.abs(actual - pred)
    top_n = np.argsort(resid)[::-1][:6]
    label_set = set(top_n)

    fig = go.Figure()

    # ── Quadrant shading ─────────────────────────────────────────────────────
    # Correct direction: upper-right (actual>0, pred>0) + lower-left (<0,<0)
    mid = 0.0
    shade_correct = 'rgba(46,125,74,0.07)'
    shade_wrong   = 'rgba(194,58,58,0.07)'

    # lower-left correct
    fig.add_shape(type='rect', x0=lims[0], x1=mid, y0=lims[0], y1=mid,
                  fillcolor=shade_correct, line=dict(width=0), layer='below')
    # upper-right correct
    fig.add_shape(type='rect', x0=mid, x1=lims[1], y0=mid, y1=lims[1],
                  fillcolor=shade_correct, line=dict(width=0), layer='below')
    # upper-left wrong (actual<0, pred>0)
    fig.add_shape(type='rect', x0=lims[0], x1=mid, y0=mid, y1=lims[1],
                  fillcolor=shade_wrong,   line=dict(width=0), layer='below')
    # lower-right wrong (actual>0, pred<0)
    fig.add_shape(type='rect', x0=mid, x1=lims[1], y0=lims[0], y1=mid,
                  fillcolor=shade_wrong,   line=dict(width=0), layer='below')

    # 45° line
    fig.add_trace(go.Scatter(
        x=[lims[0], lims[1]], y=[lims[0], lims[1]],
        mode='lines', line=dict(color=PALETTE['red'], width=1.5, dash='dash'),
        name='45° line', showlegend=True,
    ))

    # OLS fit
    fig.add_trace(go.Scatter(
        x=x_t.tolist(), y=p(x_t).tolist(),
        mode='lines', line=dict(color=PALETTE['green'], width=2),
        name=f'OLS fit (slope={z[0]:.2f})',
    ))

    # Scatter: non-outliers
    mask_normal = np.ones(len(actual), dtype=bool)
    mask_normal[list(label_set)] = False
    fig.add_trace(go.Scatter(
        x=actual[mask_normal], y=pred[mask_normal],
        mode='markers',
        marker=dict(size=7, color=PALETTE['blue'], opacity=0.65,
                    line=dict(color='white', width=0.5)),
        name='Test observations',
        customdata=np.stack([codes[mask_normal], names[mask_normal]], axis=1),
        hovertemplate='<b>%{customdata[1]}</b> (%{customdata[0]})<br>'
                      'Actual: %{x:.3f}<br>Predicted: %{y:.3f}<extra></extra>',
    ))

    # Scatter: outliers (labelled)
    out_idx = list(label_set)
    fig.add_trace(go.Scatter(
        x=actual[out_idx], y=pred[out_idx],
        mode='markers+text',
        marker=dict(size=9, color=PALETTE['orange'], opacity=0.9,
                    line=dict(color='white', width=1)),
        text=codes[out_idx],
        textposition='top center',
        textfont=dict(size=9, color='#333'),
        name='Largest residuals',
        customdata=np.stack([codes[out_idx], names[out_idx]], axis=1),
        hovertemplate='<b>%{customdata[1]}</b><br>'
                      'Actual: %{x:.3f}<br>Predicted: %{y:.3f}<extra></extra>',
    ))

    # Zero axes
    fig.add_hline(y=0, line=dict(color=GRID, width=1))
    fig.add_vline(x=0, line=dict(color=GRID, width=1))

    fig.update_layout(**base_layout(
        height=600,
        margin=dict(l=70, r=80, t=80, b=70),
        xaxis=dict(
            title=dict(text='Actual ECI (test set 2015–2019)', font=dict(size=13)),
            range=lims, gridcolor=GRID, gridwidth=0.5,
        ),
        yaxis=dict(
            title=dict(text='Predicted ECI', font=dict(size=13)),
            range=lims, gridcolor=GRID, gridwidth=0.5,
        ),
        legend=dict(
            font=dict(size=10), bgcolor='rgba(250,250,250,0.9)',
            bordercolor=GRID, borderwidth=1,
        ),
    ))
    save(fig, 'chart12_actual_vs_predicted', w=950, h=600)


# =============================================================================
# CHART 13 — ECI Forecast Trajectories (confidence band + forecast annotation)
# =============================================================================
def chart13_forecast_trajectories():
    """
    Forecast trajectory improvements:
    - Vertical grey band marking the forecast period (2020–2030)
    - Shaded ±RMSE confidence band around each country's ensemble forecast
    - Better color contrast via a fixed high-contrast palette
    - Historical solid + forecast dashed with same colour per country
    """
    fc   = pd.read_csv(os.path.join(NB5, 'ECI_Forecast_2020_2030.csv'))
    rank = pd.read_csv(os.path.join(NB5, 'Country_Ranking_2020_2030.csv'))
    perf = pd.read_csv(os.path.join(NB5, 'model_performance_level.csv'))

    # Historical ECI from Master.csv
    master = pd.read_csv('intermediary/Master.csv')
    hist   = master[['Country Code', 'Country Name', 'Year',
                      'Economic Complexity Index']].dropna()

    # Top 6 improvers
    top6_codes = rank.head(6)['Country Code'].tolist()
    hist_top = hist[hist['Country Code'].isin(top6_codes)]

    # RMSE from best model (for uncertainty band)
    best_rmse = perf.iloc[0]['Test RMSE'] if 'Test RMSE' in perf.columns else 0.08

    # High-contrast palette (6 colours)
    COLORS = ['#4a6fa5', '#c23a3a', '#2e7d4a', '#d4853b', '#7a5c9e', '#3a8fa5']

    fig = go.Figure()

    # Grey forecast band (background rectangle 2020→2030)
    fig.add_vrect(
        x0=2019.5, x1=2030.5,
        fillcolor='rgba(200,210,225,0.18)',
        line=dict(width=0),
        layer='below',
    )
    fig.add_vline(x=2019.5, line=dict(color='#aaa', width=1.5, dash='dot'))

    for i, cc in enumerate(top6_codes):
        col   = COLORS[i % len(COLORS)]
        cname = rank[rank['Country Code'] == cc]['Country'].values[0]

        # Historical
        h = hist_top[hist_top['Country Code'] == cc].sort_values('Year')
        fig.add_trace(go.Scatter(
            x=h['Year'], y=h['Economic Complexity Index'],
            mode='lines',
            line=dict(color=col, width=2.5),
            name=cname,
            legendgroup=cc,
            hovertemplate=f'<b>{cname}</b><br>%{{x}}: %{{y:.3f}}<extra>Historical</extra>',
        ))

        # Forecast ensemble
        f = fc[fc['Country Code'] == cc].sort_values('Year')
        ens = f['Ensemble'].values
        yrs = f['Year'].values

        # Confidence band (±1 RMSE)
        fig.add_trace(go.Scatter(
            x=np.concatenate([yrs, yrs[::-1]]).tolist(),
            y=np.concatenate([ens + best_rmse, (ens - best_rmse)[::-1]]).tolist(),
            fill='toself',
            fillcolor=f'rgba({",".join(str(int(c)) for c in _hex_to_rgb(col))},0.10)',
            line=dict(color='rgba(0,0,0,0)'),
            showlegend=False,
            hoverinfo='skip',
            legendgroup=cc,
        ))

        # Forecast line (dashed, same colour)
        # Bridge gap: start from last historical point
        last_hist = h.sort_values('Year').tail(1)
        x_bridge = [int(last_hist['Year'].values[0])] + yrs.tolist()
        y_bridge = [float(last_hist['Economic Complexity Index'].values[0])] + ens.tolist()
        fig.add_trace(go.Scatter(
            x=x_bridge, y=y_bridge,
            mode='lines',
            line=dict(color=col, width=2.5, dash='dash'),
            showlegend=False,
            legendgroup=cc,
            hovertemplate=f'<b>{cname}</b><br>%{{x}}: %{{y:.3f}}<extra>Forecast</extra>',
        ))

    # Y-range from all data
    all_eci = pd.concat([
        hist_top['Economic Complexity Index'],
        fc[fc['Country Code'].isin(top6_codes)]['Ensemble'],
    ]).dropna()

    fig.update_layout(**base_layout(
        height=620,
        margin=dict(l=70, r=60, t=80, b=70),
        xaxis=dict(
            title=dict(text='Year', font=dict(size=13)),
            gridcolor=GRID, gridwidth=0.5,
            dtick=5,
        ),
        yaxis=dict(
            title=dict(text='Economic Complexity Index', font=dict(size=13)),
            range=[all_eci.min() - 0.15, all_eci.max() + 0.15],
            gridcolor=GRID, gridwidth=0.5,
        ),
        legend=dict(
            font=dict(size=11), bgcolor='rgba(250,250,250,0.9)',
            bordercolor=GRID, borderwidth=1,
            x=0.01, y=0.99, xanchor='left', yanchor='top',
        ),
    ))
    save(fig, 'chart13_forecast_trajectories', w=1100, h=620)


def _hex_to_rgb(h):
    h = h.lstrip('#')
    return tuple(int(h[i:i+2], 16) for i in (0, 2, 4))


# =============================================================================
# RUNNER
# =============================================================================
if __name__ == '__main__':
    tasks = [
        ('Chart 8  — Model Agreement',           chart8_model_agreement),
        ('Chart 9  — Standardised Coefficients', chart9_coefficient_comparison),
        ('Chart 10 — RF Importance + EN ref',    chart10_rf_importance),
        ('Chart 11 — Train vs Test R² (Cleveland)', chart11_train_vs_test),
        ('Chart 12 — Actual vs Predicted',        chart12_actual_vs_predicted),
        ('Chart 13 — Forecast Trajectories',      chart13_forecast_trajectories),
    ]

    results = {}
    for name, fn in tasks:
        print(f"\n{'='*60}")
        print(f"  {name}")
        print('='*60)
        try:
            fn()
            results[name] = 'OK'
        except Exception as e:
            import traceback
            print(f"  FAILED: {e}")
            traceback.print_exc()
            results[name] = f'FAIL: {e}'

    print(f"\n{'='*60}")
    print('SUMMARY')
    print('='*60)
    for name, status in results.items():
        icon = '✓' if status == 'OK' else '✗'
        print(f"  {icon}  {name}: {status}")
    print(f"\nOutputs in: {OUT}/")
